/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef APP_H
#define APP_H

#endif
#include <string>
#include <iostream>
#include <vector>
#include <list>	
#include <set>
#include <map>	
#include "solution.h"
using namespace std;
