/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#include "app.h"
int main()
{
    Solution s;
    vector<int> numbers={2, 7, 11, 15};
    int target = 18;
    vector<int> outcome = s.twoSum(numbers, target);
    for (int i = 0; i < outcome.size(); i++) {
            cout << outcome[i] << " ";
        }
        cout << endl;
    return 0;
}
